version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - 3000:3000
    environment:
      MONGODB_URL: mongodb://db:27017
    volumes:
      - ./src:/app/src
    depends_on:
      - db

  db:
    image: mongo
    restart: always
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: {}